# Kategorilere ayrılmış tam liste
ALL_DAX_FUNCTIONS = {
    "Date and Time": [
        "CALENDAR", "CALENDARAUTO", "DATE", "DATEDIFF", "DATEVALUE", "DAY",
        "EDATE", "EOMONTH", "HOUR", "MINUTE", "MONTH", "NETWORKDAYS", "NOW",
        "QUARTER", "SECOND", "TIME", "TIMEVALUE", "TODAY", "UTCNOW", "UTCTODAY",
        "WEEKDAY", "WEEKNUM", "YEAR", "YEARFRAC"
    ],
    "Time Intelligence": [
        "CLOSINGBALANCEMONTH", "CLOSINGBALANCEQUARTER", "CLOSINGBALANCEYEAR",
        "DATEADD", "DATESBETWEEN", "DATESINPERIOD", "DATESMTD", "DATESQTD",
        "DATESYTD", "ENDOFMONTH", "ENDOFQUARTER", "ENDOFYEAR", "FIRSTDATE",
        "FIRSTNONBLANK", "FIRSTNONBLANKVALUE", "LASTDATE", "LASTNONBLANK",
        "LASTNONBLANKVALUE", "NEXTDAY", "NEXTMONTH", "NEXTQUARTER", "NEXTYEAR",
        "OPENINGBALANCEMONTH", "OPENINGBALANCEQUARTER", "OPENINGBALANCEYEAR",
        "PARALLELPERIOD", "PREVIOUSDAY", "PREVIOUSMONTH", "PREVIOUSQUARTER",
        "PREVIOUSYEAR", "SAMEPERIODLASTYEAR", "STARTOFMONTH", "STARTOFQUARTER",
        "STARTOFYEAR", "TOTALMTD", "TOTALQTD", "TOTALYTD"
    ],
    "Filter": [
        "ALL", "ALLCROSSFILTERED", "ALLEXCEPT", "ALLNOBLANKROW", "ALLSELECTED",
        "CALCULATE", "CALCULATETABLE", "CROSSFILTER", "EARLIER", "EARLIEST",
        "FILTER", "INDEX", "KEEPFILTERS", "LOOKUPVALUE", "MATCHBY", "OFFSET",
        "ORDERBY", "PARTITIONBY", "RANK", "REMOVEFILTERS", "SELECTEDVALUE",
        "TREATAS", "USERELATIONSHIP", "WINDOW"
    ],
    "Financial": [
        "ACCRINT", "ACCRINTM", "AMORDEGRC", "AMORLINC", "COUPDAYBS", "COUPDAYS",
        "COUPDAYSNC", "COUPNCD", "COUPNUM", "COUPPCD", "CUMIPMT", "CUMPRINC",
        "DB", "DDB", "DISC", "DOLLARDE", "DOLLARFR", "DURATION", "EFFECT",
        "FV", "FVSCHEDULE", "INTRATE", "IPMT", "IRR", "ISPMT", "MDURATION",
        "MIRR", "NOMINAL", "NPER", "NPV", "ODDFPRICE", "ODDFYIELD", "ODDLPRICE",
        "ODDLYIELD", "PDURATION", "PMT", "PPMT", "PRICE", "PRICEDISC",
        "PRICEMAT", "PV", "RATE", "RECEIVED", "RRI", "SLN", "SYD", "TBILLEQ",
        "TBILLPRICE", "TBILLYIELD", "VDB", "XIRR", "XNPV", "YIELD", "YIELDDISC",
        "YIELDMAT"
    ],
    "Information": [
        "COLUMNSTATISTICS", "CONTAINS", "CONTAINSROW", "CONTAINSSTRING",
        "CONTAINSSTRINGEXACT", "CUSTOMDATA", "ISAFTER", "ISBLANK",
        "ISCROSSFILTERED", "ISEMPTY", "ISERROR", "ISEVEN", "ISFILTERED",
        "ISINSCOPE", "ISLOGICAL", "ISNONTEXT", "ISNUMBER", "ISODD",
        "ISONORAFTER", "ISSELECTEDMEASURE", "ISSUBTOTAL", "ISTEXT",
        "NONVISUAL", "SELECTEDMEASURE", "SELECTEDMEASUREFORMATSTRING",
        "SELECTEDMEASURENAME", "USERCULTURE", "USERNAME", "USEROBJECTID",
        "USERPRINCIPALNAME"
    ],
    "Logical": [
        "AND", "BITAND", "BITLSHIFT", "BITOR", "BITRSHIFT", "BITXOR",
        "COALESCE", "FALSE", "IF", "IF.EAGER", "IFERROR", "NOT", "OR",
        "SWITCH", "TRUE"
    ],
    "Math and Trig": [
        "ABS", "ACOS", "ACOSH", "ACOT", "ACOTH", "ASIN", "ASINH", "ATAN",
        "ATANH", "CEILING", "COMBIN", "COMBINA", "CONVERT", "COS", "COSH",
        "CURRENCY", "DEGREES", "DIVIDE", "EVEN", "EXP", "FACT", "FLOOR",
        "GCD", "INT", "ISO.CEILING", "LCM", "LN", "LOG", "LOG10", "MOD",
        "MROUND", "ODD", "PI", "POWER", "PRODUCT", "QUOTIENT", "RADIANS",
        "RAND", "RANDBETWEEN", "ROUND", "ROUNDDOWN", "ROUNDUP", "SIGN",
        "SIN", "SINH", "SQRT", "SQRTPI", "SUM", "SUMX", "TAN", "TANH", "TRUNC"
    ],
    "Statistical": [
        "APPROXIMATEDISTINCTCOUNT", "AVERAGE", "AVERAGEA", "AVERAGEX",
        "BETA.DIST", "BETA.INV", "CHISQ.DIST", "CHISQ.DIST.RT", "CHISQ.INV",
        "CHISQ.INV.RT", "CONFIDENCE.NORM", "CONFIDENCE.T", "COUNT", "COUNTA",
        "COUNTAX", "COUNTBLANK", "COUNTROWS", "COUNTX", "DISTINCTCOUNT",
        "DISTINCTCOUNTNOBLANK", "EXPON.DIST", "GEOMEAN", "GEOMEANX", "KURT",
        "LINEST", "LINESTX", "MAX", "MAXA", "MAXX", "MEDIAN", "MEDIANX",
        "MIN", "MINA", "MINX", "NORM.DIST", "NORM.INV", "NORM.S.DIST",
        "NORM.S.INV", "PERCENTILE.EXC", "PERCENTILE.INC", "PERCENTILEX.EXC",
        "PERCENTILEX.INC", "PERMUT", "POISSON.DIST", "RANK.EQ", "RANKX",
        "SAMPLE", "STDEV.P", "STDEV.S", "STDEVX.P", "STDEVX.S", "T.DIST",
        "T.DIST.2T", "T.DIST.RT", "T.INV", "T.INV.2T", "TOPN", "TTEST",
        "VAR.P", "VAR.S", "VARX.P", "VARX.S"
    ],
    "Text": [
        "COMBINEVALUES", "CONCATENATE", "CONCATENATEX", "EXACT", "FIND",
        "FIXED", "FORMAT", "LEFT", "LEN", "LOWER", "MID", "REPLACE", "REPT",
        "RIGHT", "SEARCH", "SUBSTITUTE", "TRIM", "UNICHAR", "UNICODE",
        "UPPER", "VALUE"
    ],
    "Parent-Child": [
        "PATH", "PATHCONTAINS", "PATHITEM", "PATHITEMREVERSE", "PATHLENGTH"
    ],
    "Table Manipulation": [
        "ADDCOLUMNS", "ADDMISSINGITEMS", "CROSSJOIN", "CURRENTGROUP",
        "DATATABLE", "DISTINCT", "EXCEPT", "FILTERS", "GENERATE",
        "GENERATEALL", "GROUPBY", "IGNORE", "INTERSECT",
        "NATURALINNERJOIN", "NATURALLEFTOUTERJOIN", "ROLLUP",
        "ROLLUPADDISSUBTOTAL", "ROLLUPISSUBTOTAL", "ROW", "SELECTCOLUMNS",
        "SUMMARIZE", "SUMMARIZECOLUMNS", "TOPN", "TREATAS", "UNION", "VALUES"
    ],
    "Other": [
        "ERROR", "EVALUATEANDLOG", "INFO", "INFO.ATTRIBUTEHIERARCHIES",
        "INFO.CALCDEPENDENCY", "INFO.CALCMETADATA", "INFO.COLUMNS",
        "INFO.DATASOURCES", "INFO.FUNCTIONS", "INFO.GROUPS",
        "INFO.INDICES", "INFO.MEASURES", "INFO.PARTITIONS",
        "INFO.RELATIONSHIPS", "INFO.TABLES", "INFO.USERROLECONFIGURATIONS"
    ]
}